---
name: Ubuntu 20.04

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches: []

jobs:
  ubuntu-2004:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --tag ${{ github.repository_owner }}-ubuntu2004 docker/ubuntu/20.04
      - name: Test Galaxy role
        run: >
            docker run --rm -v ${{ github.workspace }}:/repo ${{ github.repository_owner }}-ubuntu2004 /bin/bash -c
            "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml; fi &&
            ANSIBLE_ROLES_PATH=.. ANSIBLE_FORCE_COLOR=true ansible-playbook tests/main.yml"
